<!-- Documentation Project from freecodecamp.org
This is one of the Responsive Web Design Certification projects.
You can use HTML, JavaScript, and CSS to complete this project. Plain CSS is recommended because that is what the lessons have covered so far and you should get some practice with plain CSS.
Required:
User Story #1: I can see a main element with a corresponding id="main-doc", which contains the page's main content (technical documentation).

User Story #2: Within the #main-doc element, I can see several section elements, each with a class of main-section. There should be a minimum of 5.

User Story #3: The first element within each .main-section should be a header element which contains text that describes the topic of that section.

User Story #4: Each section element with the class of main-section should also have an id that corresponds with the text of each header contained within it. Any spaces should be replaced with underscores (e.g. The section that contains the header "JavaScript and Java" should have a corresponding id="JavaScript_and_Java").

User Story #5: The .main-section elements should contain at least 10 p elements total (not each).

User Story #6: The .main-section elements should contain at least 5 code elements total (not each).

User Story #7: The .main-section elements should contain at least 5 li items total (not each).

User Story #8: I can see a nav element with a corresponding id="navbar".

User Story #9: The navbar element should contain one header element which contains text that describes the topic of the technical documentation.

User Story #10: Additionally, the navbar should contain link (a) elements with the class of nav-link. There should be one for every element with the class main-section.

User Story #11: The header element in the navbar must come before any link (a) elements in the navbar.

User Story #12: Each element with the class of nav-link should contain text that corresponds to the header text within each section (e.g. if you have a "Hello world" section/header, your navbar should have an element which contains the text "Hello world").

User Story #13: When I click on a navbar element, the page should navigate to the corresponding section of the main-doc element (e.g. If I click on a nav-link element that contains the text "Hello world", the page navigates to a section element that has that id and contains the corresponding header.

User Story #14: On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

User Story #15: My Technical Documentation page should use at least one media query.
This technical documentation page is about promises() documentation.

-->
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Technical Documentation Page</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,700;1,300;1,400;1,600;1,800&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="style.css">
</head>

<body>

  <div id="container">
    <!--container-div-->

    <!-- nav section -->
    <nav id="navbar">
      <header>
        Promises() Documentation
      </header>
      <div id="scroll">
        <hr>
        <a class="nav-link" href="#using_promises">Using Promises</a>
        <hr>
        <a class="nav-link" href="#guarantees">Guarantees</a>
        <hr>
        <a class="nav-link" href="#chaining"> Chaining</a>
        <hr>
        <a class="nav-link" href="#error_propagation">Error propagation</a>
        <hr>
        <a class="nav-link" href="#promise_rejection_events">Promise rejection events</a>
        <hr>
        <a class="nav-link" href="#creating_a_promise_around_an_old_callback_API">Creating a Promise around an old
          callback API</a>
        <hr>
        <a class="nav-link" href="#composition">Composition</a>
        <hr>
      </div>
    </nav>

    <!--main section -->
    <main id="main-doc">
      <section class="main-section" id="using_promises">
        <header>Using Promises</header>
        <p>A Promise is an object representing the eventual completion or failure of an asynchronous operation. Since
          most people are consumers of already-created promises, this guide will explain consumption of returned
          promises before explaining how to create them.

          Essentially, a promise is a returned object to which you attach callbacks, instead of passing callbacks into a
          function.

          Imagine a function, createAudioFileAsync(), which asynchronously generates a sound file given a configuration
          record and two callback functions, one called if the audio file is successfully created, and the other called
          if an error occurs.

          Here's some code that uses createAudioFileAsync():</p>
        <code>
                      function successCallback(result) {
                        console.log("Audio file ready at URL: " + result);
                          }
                          
                          function failureCallback(error) {
                            console.error("Error generating audio file: " + error);
                          }
                      
                      createAudioFileAsync(audioSettings, successCallback, failureCallback);
                    </code>
        <p>
          If createAudioFileAsync() were rewritten to return a promise, you would attach your callbacks to it instead:
        </p>
        <code>
                  createAudioFileAsync(audioSettings).then(successCallback, failureCallback);
                </code>
        <p>This convention has several advantages. We will explore some here.</p>
      </section>

      <section class="main-section" id="guarantees">
        <header>Guarantees</header>
        <p> Unlike old-fashioned passed-in callbacks, a promise comes with some guarantees: </p>
        <ul>
          <li> Callbacks added with then() will never be invoked before the completion of the current run of the
            JavaScript event loop.</li>
          <li>These callbacks will be invoked even if they were added after the success or failure of the asynchronous
            operation that the promise represents</li>
          <li>Multiple callbacks may be added by calling then() several times. They will be invoked one after another,
            in the order in which they were inserted.</li>
        </ul>
        <p> One of the great things about using promises is chaining.</p>
      </section>
      <section class="main-section" id="chaining">
        <header>Chaining</header>

        <p> A common need is to execute two or more asynchronous operations back to back, where each subsequent
          operation starts when the previous operation succeeds, with the result from the previous step. We accomplish
          this by creating a promise chain.

          Here's the magic: the then() function returns a new promise, different from the original: </p>

        <code>
                    const promise = doSomething();
                    const promise2 = promise.then(successCallback, failureCallback);
                  
                    or
                    
                    const promise2 = doSomething().then(successCallback, failureCallback);
                    </code>
        <p>
          This second promise (promise2) represents the completion not just of doSomething(), but also of the
          successCallback or failureCallback you passed in, which can be other asynchronous functions returning a
          promise. When that's the case, any callbacks added to promise2 get queued behind the promise returned by
          either successCallback or failureCallback.

          Basically, each promise represents the completion of another asynchronous step in the chain.

          In the old days, doing several asynchronous operations in a row would lead to the classic callback pyramid of
          doom: </p>

        <code>
           doSomething(function(result) {
             doSomethingElse(result, function(newResult) {
               doThirdThing(newResult, function(finalResult) {
                 console.log('Got the final result: ' + finalResult);
               }, failureCallback);
             }, failureCallback);
           }, failureCallback);
          </code>
        With modern functions, we attach our callbacks to the returned promises instead, forming a promise chain:
        <code>
           doSomething()
           .then(function(result) {
             return doSomethingElse(result);
                })
                .then(function(newResult) {
                  return doThirdThing(newResult);
                })
                .then(function(finalResult) {
                  console.log('Got the final result: ' + finalResult);
              })
           .catch(failureCallback);
          </code>
        <p>
          The arguments to then are optional, and catch(failureCallback) is short for then(null, failureCallback). You
          might see this expressed with arrow functions instead:</p>
        <code>
            doSomething()
             .then(result => doSomethingElse(result))
                .then(newResult => doThirdThing(newResult))
                .then(finalResult => {
                  console.log(`Got the final result: ${finalResult}`);
                })
           .catch(failureCallback);
          </code>
        <p>
          Important: Always return results, otherwise callbacks won't catch the result of a previous promise (with arrow
          functions () => x is short for () => { return x; }).</p>
      </section>


      <section class="main-section" id="error_propagation">
        <header>Error propagation</header>

        <p>You might recall seeing failureCallback three times in the pyramid of doom earlier, compared to only once at
          the end of the promise chain:</p>
        <code>
            doSomething()
            .then(result => doSomethingElse(result))
            .then(newResult => doThirdThing(newResult))
            .then(finalResult => console.log(`Got the final result: ${finalResult}`))
            .catch(failureCallback);
          </code>
        <p> If there's an exception, the browser will look down the chain for .catch() handlers or onRejected. This is
          very much modeled after how synchronous code works: </p>
        <code>
            try {
              const result = syncDoSomething();
              const newResult = syncDoSomethingElse(result);
              const finalResult = syncDoThirdThing(newResult);
              console.log(`Got the final result: ${finalResult}`);
            } catch(error) {
              failureCallback(error);
            }
      </code>
        <p> This symmetry with asynchronous code culminates in the async/await syntactic sugar in ECMAScript 2017:</p>
        <code>
            async function foo() {
              try {
                const result = await doSomething();
                const newResult = await doSomethingElse(result);
                const finalResult = await doThirdThing(newResult);
                console.log(`Got the final result: ${finalResult}`);
              } catch(error) {
                failureCallback(error);
              }
            }
          </code>
        <p> It builds on promises, e.g. doSomething() is the same function as before.
          Promises solve a fundamental flaw with the callback pyramid of doom, by:</p>
        <ul>
          <li>catching all errors</li>
          <li>thrown exceptions</li>
          <li>throw programming errors</li>
        </ul>
        <p> This is essential for functional composition of asynchronous operations.</p>
      </section>

      <section class="main-section" id="promise_rejection_events">
        <header> Promise rejection events </header>

        Whenever a promise is rejected, one of two events is sent to the global scope (generally, this is either the
        window or, if being used in a web worker, it's the Worker or other worker-based interface). The two events are:
        <ul>
          <li>rejectionhandled <br>
            Sent when a promise is rejected, after that rejection has been handled by the executor's reject function.
          </li>
          <li>unhandledrejection <br>
            Sent when a promise is rejected but there is no rejection handler available.</li>
        </ul>

        <p>In both cases, the event (of type PromiseRejectionEvent) has as members a promise property indicating the
          promise that was rejected, and a reason property that provides the reason given for the promise to be
          rejected.

          These make it possible to offer fallback error handling for promises, as well as to help debug issues with
          your promise management. These handlers are global per context, so all errors will go to the same event
          handlers, regardless of source.</p>

        <p>One case of special usefulness: when writing code for Node.js, it's common that modules you include in your
          project may have unhandled rejected promises, logged to the console by the Node.js runtime. You can capture
          them for analysis and handling by your code—or just to avoid having them cluttering up your output—by adding a
          handler for the Node.js unhandledRejection event (notice the difference in capitalization of the name), like
          this:</p>
        <code>
      process.on("unhandledRejection", (reason, promise) => {
        /* You might start here by adding code to examine the
         * "promise" and "reason" values. */
      });
      </code>
        <p>For Node.js, to prevent the error from being logged to the console (the default action that would otherwise
          occur), adding that process.on() listener is all that necessary; there's no need for an equivalent of the
          browser runtime’s preventDefault() method.</p>

        <p>However, if you add that process.on listener but don't also have code within it to handle rejected promises,
          they will just be dropped on the floor and silently ignored. So ideally, you should add code within that
          listener to examine each rejected promise and make sure it was not caused by an actual code bug.</p>
      </section>
      <section class="main-section" id="creating_a_promise_around_an_old_callback_API">
        <header>Creating a promise around an old callback API </header>

        <p>A Promise can be created from scratch using its constructor. This should be needed only to wrap old APIs.

          In an ideal world, all asynchronous functions would already return promises. Unfortunately, some APIs still
          expect success and/or failure callbacks to be passed in the old way. The most obvious example is the
          setTimeout() function:</p>
        <code>
      setTimeout(() => saySomething("10 seconds passed"), 10*1000);
      </code>
        <p>Mixing old-style callbacks and promises is problematic. If saySomething() fails or contains a programming
          error, nothing catches it. setTimeout is to blame for this.

          Luckily we can wrap setTimeout in a promise. Best practice is to wrap problematic functions at the lowest
          possible level, and then never call them directly again:</p>
        <code>
                const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
      
                wait(10*1000).then(() => saySomething("10 seconds")).catch(failureCallback);
            </code>
        <p>Basically, the promise constructor takes an executor function that lets us resolve or reject a promise
          manually. Since setTimeout() doesn't really fail, we left out reject in this case.</p>
      </section>
      <section class="main-section" id="composition">
        <header>Composition</header>
        Promise.resolve() and Promise.reject() are shortcuts to manually create an already resolved or rejected promise
        respectively. This can be useful at times.

        Promise.all() and Promise.race() are two composition tools for running asynchronous operations in parallel.

        We can start operations in parallel and wait for them all to finish like this:
        <code>
           Promise.all([func1(), func2(), func3()])
           .then(([result1, result2, result3]) => { /* use result1, result2 and result3 */ });
          </code>
        Sequential composition is possible using some clever JavaScript:
        <code>
           [func1, func2, func3].reduce((p, f) => p.then(f), Promise.resolve())
           .then(result3 => { /* use result3 */ });
          </code>
        Basically, we reduce an array of asynchronous functions down to a promise chain equivalent to:
        Promise.resolve().then(func1).then(func2).then(func3);

        This can be made into a reusable compose function, which is common in functional programming:
        <code>
           const applyAsync = (acc,val) => acc.then(val);
           const composeAsync = (...funcs) => x => funcs.reduce(applyAsync, Promise.resolve(x));
          </code>
        The composeAsync() function will accept any number of functions as arguments, and will return a new function
        that accepts an initial value to be passed through the composition pipeline:
        <code>
           const transformData = composeAsync(func1, func2, func3);
           const result3 = transformData(data);
          </code>
        In ECMAScript 2017, sequential composition can be done more with async/await:
        <code>
           let result;
           for (const f of [func1, func2, func3]) {
             result = await f(result);
           }
           /* use last result (i.e. result3) */  
          </code>
      </section>
      <div>
        <p>For other advantages of promises below, you can refer to MDN documentation</p>
        <ul>
          <li>Timing</li>
          <li>Nesting</li>
          <li>Common mistakes</li>
          <li>When promises and tasks collide</li>
        </ul>
      </div>
      <footer>
        <span>Reference</span>
        <p> All the documentation in this page is taken from <a
            href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#promise_rejection_events">MDN</a>
        </p>
        <p>This site was built and maintained by XYZ. &copy;2022 Jone Doe St, New York</p>
      </footer>
    </main>
    <!--End of main-->
  </div>
  <!--End container div-->

</body>

</html>